languageCode = "es-pe"
languageName = "Español"
weight = 1

title = "spelucin.me"
copyright = "&copy; 2023 - Alex Spelucín"

[params]
  isoCode = "es-PE"
  displayName = ":flag-pe:"
  rtl = false

  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Consultor SEO, especialista en SEO Técnico y análisis de datos. Trabajando desde Lima, Perú."

[author]
  name = "Alex Spelucín"
  image = "img/alex-spelucin-consultor-seo.jpg"
  headline = "Especialista en SEO Técnico"
  bio = "Consultor SEO, especialista en SEO Técnico y análisis de datos de Perú. Cinco años de aprender y desaprender sobre los motores de búsqueda. Programador aficionado de JavaScript. Padre y esposo orgulloso."
  links = [
    { linkedin = "https://www.linkedin.com/in/spelucin/" },
    { github = "https://github.com/spelucin" },
    { mastodon = "https://mstdn.social/@spelucin" },
    { email = "spelucinalex@gmail.com" }
  ]
