languageCode = "es"
languageName = "Español"
languageDirection = "ltr"
weight = 1

title = "spelucin.me"
copyright = "&copy; 2023 - Alex Spelucín"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Analista digital web. Me encargo de que la data sea la gasolina de tu marketing digital. Trabajando desde Lima, Perú"

[author]
  name = "Alex Spelucín"
  image = "img/alex-spelucin-analista-digital.jpg"
  headline = "Especialista en analítica digital y web"
  bio = "Analista digital y web. Especializado en Google Marketing Platform. Relación de amor-odio con Google Tag Manager, besito para BigQuery. Padre orgulloso y esposo enamorado."
  links = [
    { linkedin = "https://www.linkedin.com/in/spelucin/" },
    { github = "https://github.com/spelucin" },
    { mastodon = "https://mstdn.social/@spelucin" },
    { email = "spelucinalex@gmail.com" }
  ]