languageCode = "es"
languageName = "Español"
languageDirection = "ltr"
weight = 1

title = "spelucin.online"
copyright = "&copy; 2023 - Alex Spelucín"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Analista digital web. Me encargo de que la data sea la gasolina de tu marketing digital. Trabajando desde Lima, Perú"

[author]
  name = "Alex Spelucín"
  image = "img/alex-spelucin-analista-digital.jpg"
  headline = "Analista digital y growth marketer"
  bio = "Analista digital y growth marketer. Malabreando datos para saber qué funciona (y qué no) en el marketing digital. Padre orgulloso y esposo enamorado."
  links = [
    { linkedin = "https://www.linkedin.com/in/spelucin/" },
    { github = "https://github.com/spelucin" },
    { mastodon = "https://mstdn.social/@spelucin" },
    { email = "spelucinalex@gmail.com" }
  ]