languageCode = "es"
languageName = "Español"
languageDirection = "ltr"
weight = 1

title = "spelucin.me"
copyright = "&copy; 2023 - Alex Spelucín"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Consultor SEO, orientado a sitios que necesitan generar leads y citas en linea. Trabajando desde Lima, Perú."

[author]
  name = "Alex Spelucín"
  image = "img/alex-spelucin-consultor-seo.jpg"
  headline = "Especialista en SEO ténico y análisis de datos"
  bio = "Consultor SEO. Tratando de entender a Google desde hace 5 años. Me paso demasiado tiempo en Google Sheets. Padre orgulloso y esposo enamorado."
  links = [
    { linkedin = "https://www.linkedin.com/in/spelucin/" },
    { github = "https://github.com/spelucin" },
    { mastodon = "https://mstdn.social/@spelucin" },
  ]